name: zefyrka
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter based on Zefyr package.
version: 1.0.6
homepage: https://github.com/glynskyi/zefyrka

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  url_launcher: ^6.0.4
  quill_format: ^1.0.2
  notus_format: ^1.0.3
  characters: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0